import React from 'react';
import ReactDOM from 'react-dom';

// import App from './01_计数器案例/App';
// import App from './02_useState/01_多个状态的定义';
// import App from './02_useState/02_复杂状态的修改';
// import App from './02_useState/03_传入函数';
// import App from './03_useEffect/01_class实现操作DOMTitle';
// import App from './03_useEffect/02_hook实现操作DOMTitle';
// import App from './03_useEffect/03_useEffect模拟订阅和取消订阅';
// import App from './03_useEffect/04_使用多个Effect';
// import App from './03_useEffect/05_Effect性能优化';
// import App from './04_useContext/01_useContext';
// import App from './05_useReducer/01_useReducer';
// import App from './06_useCallback/01_useCallback不能进行的性能优化';
// import App from './06_useCallback/02_useCallback能进行的性能优化';
// import App from './07_useMemo/01_复杂计算的应用';
// import App from './07_useMemo/02_向子组件传递引用数据类型的应用';
// import App from './08_useRef/01_引入DOM';
// import App from './08_useRef/02_保存数据';
// import App from './08_useRef/03_展示新值和上一次的值';
// import App from './09_useImperativeHandle/01_ref和forwardRef的结合使用';
// import App from './09_useImperativeHandle/02_useImperativeHandle';
// import App from './10_useLayoutEffect/01_useEffect';
// import App from './10_useLayoutEffect/02_useLayoutEffect';
// import App from './11_自定义hook/01_日志打印';
// import App from './11_自定义hook/02_Context的共享/App';
// import App from './11_自定义hook/03_获取页面滚动位置/App';
import App from './11_自定义hook/04_localStorage数据存储/App';

ReactDOM.render(<App />, document.getElementById('root'));
